config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comics, except: [:destroy] do
    delete '/:id', to: 'comics#destroy', as: 'delete', on: :collection
  end

  get "/users/:user_id", to: "users#show", as: 'user_profile'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "/transactions/", to: 'transactions#index'
  post "/transactions/", to: 'transactions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comic.rb
class Comic < ApplicationRecord
  belongs_to :user
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :comic 
  belongs_to :buyer, class_name: 'User'
  belongs_to :seller, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable, :trackable, :validatable
    has_many :comics
    validates :username, presence: true
    # has_attached_file :logo, styles: {:medium => "300x300>", :thumb => "100x100>"}
    # validates_attachment_content_type :logo, :content_type => /\Aimage\/.*\z/
    has_many :transactions, foreign_key: 'seller_id'
    has_many :transactions, foreign_key: 'buyer_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end


end

app/controllers/comics_controller.rb
class ComicsController < ApplicationController
    def index
        @comics = Comic.all
        @transaction = Transaction.new
        render 'index'
    end

    def new
        @comics = Comic.new
        # Pilla los params para hacer un nuevo comic
    end

    def create
        @my_comic = Comic.new(
            title: params[:comic][:title],
            author: params[:comic][:author],
            year: params[:comic][:year],
            publisher: params[:comic][:publisher],
            user_id: current_user.id,
            price: params[:comic][:price]
        )
        @my_comic.save
      redirect_to "/users/#{current_user.id}/"
    end

    def show
        # Enseñame este comic concreto. Despues de hacer el post
        @comic = current_user.comics.find(params[:id])
        @user = User.find_by(id: current_user.id)
        render 'show'
        # @comics_from_user = @User.comics.all
    end

    def edit
        @comic = current_user.comics.find(params[:id])
    end

    def update
        @comic = current_user.comics.find(params[:id])

        if @comic.update(comic_params)
        redirect_to "/users/#{current_user.id}/"
        else
          render "edit"
        end
    end

    def destroy
        @user = User.find_by(id: current_user.id)
        @comic = current_user.comics.find(params[:id])
        @comic.destroy
        redirect_to "/users/#{@user.id}/"
    end
end

private # Metodo que solo se puede ejecutar dentro de la clase

def comic_params
    params.require(:comic).permit(:title, :author, :year, :publisher, :price) # Estos params tienen que tener la key time_entry (ya lo tienen, en los params de la tabla) Esto impide que se meta algun parámetro ficticio
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  def index
    render 'index'
  end

  # debugger
  # @comic = Comics.find(params[:id])
  # @comic_seller = Comics.find(params[:user_id])

  def create
    @my_transaction = Transaction.new(
        buyer_id: params[:buyer_id],
        seller_id: params[:seller_id],
        comic_id: params[:comic_id]
    )
    @my_transaction.save
        redirect_to "/transactions/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

#Antes de cada acción authenticate_user.. pero solo hazlo en show

  def index
    @users = User.all
    render 'index'
  end

  def show
    @user = User.find_by(id: current_user.id)
    @comicsfromuser = @user.comics.all
    render :show
  end

  def user_params
    params.require(:entry).permit(:username, :logo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comics/edit.html.erb
<!-- Estás aqui! Hay que cambiar la ruta, mirar la libreta!!! -->
# <%#= form_for [@my_user, @selected_comic] do |f| %>
<%= form_for @comic do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :author %>
  <%= f.text_field :author %>
  <br>
  <%= f.label :year %>
  <%= f.number_field :year %>
  <br>
  <%= f.label :publisher %>
  <%= f.text_field :publisher %>
  <br>
  <%= f.label :price %>
  <%= f.text_field :price %>
  <br>
  <%= f.button %>
  <%= link_to 'Cancel', user_profile_path(current_user) %>
<% end %>

app/views/comics/index.html.erb
<div>
<h1> All comics in database: </h1>

<% @comics.each do |comic|%>
  <ul>
  <li><%= comic.title %> </li>
  <li><%= comic.author %> </li>
  <li><%= comic.year %> </li>
  <li><%= comic.publisher %> </li>
  <% if user_signed_in? %>
  <%= button_to 'Purchase', {:controller => "transactions", :action => "create", :seller_id => comic.user_id, :buyer_id=> current_user.id, :comic_id => comic.id} , {:method=>:post}  %>
  <% end %>

</ul>
  <% end %>
  </div>

app/views/comics/new.html.erb
<div>
    <%= form_for [Comic.new] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <br>
    <%= f.label :author %>
    <%= f.text_field :author %>
    <br>
    <%= f.label :year %>
    <%= f.text_field :year %>
    <br>
    <%= f.label :publisher %>
    <%= f.text_field :publisher %>
    <br>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <br>
    <%= f.button %>
    <% end %>
</div>

app/views/comics/show.html.erb
<div>
  <ul>
    <li><%= @comic.title %></li>
    <li><%= @comic.author %></li>
    <li><%= @comic.year %></li>
    <li><%= @comic.publisher %></li>
  </ul>
  <%= link_to("Delete", "/comics/#{@comic.id}", method: :delete, data: {confirm: "Are you sure?"}) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ComicsApp</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="icon" href="../../favicon.ico">

        <!-- Bootstrap core CSS -->
        <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="starter-template.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="../../assets/js/ie-emulation-modes-warning.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]> <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script> <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script> <![endif]-->
    </head>

    <body>

        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">ComicAppp</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="active">
                            <a href="#">Home</a>
                        </li>
                        <li>
                            <a href="#about">About</a>
                        </li>
                        <li>
                            <a href="#contact">Contact</a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </nav>

        <div class="container">

            <div class="starter-template">
                <%= yield %>
            </div>
        </div>
        <!-- /.container -->

        <!-- Bootstrap core JavaScript
    ================================================== -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
        <script>
            window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')
        </script>
        <script src="../../dist/js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>

app/views/transactions/index.html.erb
<div>
    <h1>
      All these comics are in your shopping basket:
    </h1>

    <% current_user.transactions.each do |transaction|%>
    <ul>
        <li><%= transaction.comic.title %>
        </li>
    </ul>
    <% end %>
</div>

app/views/users/index.html.erb
<div>
<h1> All users in database: </h1>

<% @users.each do |user|%>
  <ul>
  <li><%= user.username %> </li>
</ul>
  <% end %>
  </div>

app/views/users/show.html.erb
<% if user_signed_in? %>
<h2> Welcome <%= current_user.username %>! </h2>
  <%= image_tag @user.logo.url %>
  <%=link_to 'Logout', destroy_user_session_path, method: 'DELETE' %>
  <br>
  <%=link_to 'Edit account', "edit" %>
  <br>
  <%= link_to "Add comic", new_comic_path(@user)%>
<p>
  All comics from this user:
</p>
<% @comicsfromuser.each do |comic|%>
<!-- Crear variable que contenga los comics de ese user -->
  <ul>
  <li><%= comic.title %> </li>
  <!-- Ruta de delete no acabada!!!! -->
  <%=link_to 'Edit comic', edit_comic_path(comic) %>
  <br>
  <%=link_to("Delete", "/comics/#{comic.id}", method: :delete, data: {confirm: "Are you sure?"})%>

</ul>
  <% end %>

<% else %>
<h2>Nobody logged in</h2>
<%end%>